"""initial migration

Revision ID: a1f4b4a99232
Revises: 
Create Date: 2023-06-14 11:36:50.436121

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1f4b4a99232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        op.add_column('project',
                      sa.Column('status', sa.String(length=20), nullable=False, server_default='defaultValue'))
        # op.drop_column('project', 'status')
        # batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('cost')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
