"""Add is_locked all column new models

Revision ID: 8ef63c3c0f55
Revises: 9b0dc16066c8
Create Date: 2023-06-20 12:48:08.517504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef63c3c0f55'
down_revision = '9b0dc16066c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False))

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
